//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4439
{
    using System;
    using System.Collections.Generic;
    
    public partial class var9
    {
        public string employe_id { get; set; }
        public string post { get; set; }
        public string fio { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string last_input { get; set; }
        public string input_type { get; set; }
    }
}
